### ISSUE TITLE
Linking against mumps libraries installed in user location

### ISSUE THREAD

**Issue by bgrishinko** [bfroehle/pymumps#3]
I'm having an issue trying to link PyMumps against my mumps installation that is installed locally rather than on the system level.

```
[khpetty@host]$ python examples/dsimpletest.py
Traceback (most recent call last):
  File "examples/dsimpletest.py", line 12, in <module>
    import mumps
  File "/gpfs/general/home/workgroups/reit/packages/pymumps/pymumps/lib/python2.7/site-packages/mumps/__init__.py", line 2, in <module>
    import _dmumps
ImportError: /gpfs/general/home/workgroups/reit/packages/pymumps/pymumps/lib/python2.7/site-packages/mumps/_dmumps.so: undefined symbol: mumps_ooc_common_mp_addvirtlibre_

```

Here is what the relevant part of my setup.py looks like:

```
 14     ext_modules=[
 15         Extension(
 16             'mumps._dmumps',
 17             sources=['mumps/_dmumps.c'],
 18             libraries=['dmumps'],
 19             library_dirs=['/gpfs/general/home/workgroups/reit/packages/pymumps/mumps/lib'],
 20             include_dirs=['/gpfs/general/home/workgroups/reit/packages/pymumps/mumps/include'],
 21         ),
 22     ],

```

I've verified that mumps itself is working and is installed locally at /gpfs/general/home/workgroups/reit/packages/pymumps/mumps/ (it is compiled with shared libraries and for parallel execution).

I'm installing with the following command:
`python setup.py install --prefix=/gpfs/general/home/workgroups/reit/packages/pymumps/PyMUMPS-0.1`

**Comment by bgrishinko** [comment]
Solved it. Looks like it was an issue of compiling mumps/scalapack after all. Despite setting flags for shared libraries, not everything was shared by default leading to the .so to be missing some of the necessary mumps symbols in _dmumps.so
