### ISSUE TITLE
Problem installing in anaconda3/Centos 6.8

### ISSUE THREAD

**Issue by ckapfer** [bfroehle/pymumps#4]
Okay a couple things ... the first is that the bundle does not include headers that mumps needs.  I have the following mumps packages installed:

$ rpm -qa|grep -i mump
MUMPS-common-5.0.2-4.el6.noarch
MUMPS-devel-5.0.2-4.el6.x86_64
MUMPS-5.0.2-4.el6.x86_64

I can get PyMUMPS to install via `python setup.py install` by sym linking the headers from /usr/include/MUMPS ... but then I get another error when trying to import the mumps package in python:

$ python
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mumps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/snapdragon/kapferc/devel/pymumps/PyMUMPS-0.1/mumps/__init__.py", line 2, in <module>
    import _dmumps
ImportError: No module named '_dmumps'

**Comment by sdrave** [comment]
Hi @ckapfer, the problem is the relative import of `_dmumps` which isn't allowed in Python 3. I have fixed this in my [fork](https://github.com/sdrave/pymumps).
